### ISSUE TITLE
Use rest_api_init to add rest_prepare hooks

### ISSUE THREAD

**Issue by luisherranz** [frontity/wp-plugins#18]
Right now we are checking for the `show_in_rest` of the custom post types in the `init` hook. It looks like sometimes people add their custom post types in the `init` hook, so we should move them to `rest_api_init`. Apart from that, we should add a low priority (50?) to allow for other plugins doing things in `rest_api_init`.

**Comment by javiersefer** [comment]
There is some quick hack to keep this working in the mean time?

**Comment by javiersefer** [comment]
Ok, for now I changed the code on my template and changed the priority to 9.
