### ISSUE TITLE
Use `wpdb` to remove all Head Tags transients

### ISSUE THREAD

**Issue by DAreRodz** [frontity/wp-plugins#19]
Currently, an option is being used to store the name of all transients. The list of transient names could be huge and this doesn't scale well. We should use `wpdb` to remove the transients based on a prefix instead of store all the names.

**Comment by DAreRodz** [comment]
Opening this again as it needs a better way to be solved.

**Comment by DAreRodz** [comment]
I'm gonna try the solution you suggested here https://github.com/frontity/wp-plugins/pull/23#issuecomment-579903965. Is that okay, @luisherranz?

**Comment by luisherranz** [comment]
Yes, sure :)
