### ISSUE TITLE
HeadTags cause failures on some REST API responses

### ISSUE THREAD

**Issue by luisherranz** [frontity/wp-plugins#20]
Our HeadTags plugin is causing some routes to fail in the REST API. I've tried to debug it, but I don't seem to find the root of the problem.

These two posts explain the issue with more detail: https://community.frontity.org/tags/cors

We also saw this behavior in wp.frontity.org and I've been able to reproduce it locally.

<img width="963" alt="Screen Shot 2020-01-24 at 18 14 00" src="https://user-images.githubusercontent.com/3305402/73092867-513b0500-3ed5-11ea-811e-d1c76c0bdebd.png">

**Comment by luisherranz** [comment]
We've found out that the problem happens because we are calling the `template_redirect` hook.

https://github.com/frontity/wp-plugins/blob/dev/plugins/frontity-headtags/includes/class-frontity-headtags.php#L142

**Comment by DAreRodz** [comment]
I think I've solved it.

The `template_redirect` hook was calling the `redirect_canonical` callback (registered by WP in `/wp-includes/default-filters.php`). That callback accepts two arguments, being one of them a boolean value that indicates if `redirect_canonical` should redirect. By default, that value is `true`, and that's the reason why the REST API requests were redirected.

I've change the `template_redirect` call and the way `redirect_canonical` is registered and now it works.

Currently, I'm doing some testing to check that the integrations are working fine too.

**Comment by DAreRodz** [comment]
Integrations are working as expected. 🙌

**Comment by luisherranz** [comment]
Awesome 👏 👏
