### ISSUE TITLE
Head Tags fails when HTML of `<head>` is malformed [3pt]

### ISSUE THREAD

**Issue by luisherranz** [frontity/wp-plugins#27]
**_Bug report_**

- I've updated both my project and my packages to the latest Frontity versions: https://docs.frontity.org/guides/keep-frontity-updated
- I've searched for existing issues.
- I've checked the documentation: https://docs.frontity.org
- I've checked the community forum: https://community.frontity.org

**Expected behavior**

The plugin should work fine even if there is an error in the HTML.

**Observed behavior**

@orballo has observed that a malformed HTML present in the `<head>` and passed to the Head Tags plugin, ends up in `DOMDocument->loadHTML()` and even though `loadHTML` deals pretty well with malformed HTML, it still outputs the warnings and therefore the REST API won't return valid JSON.

**Steps involved to reproduce the problem**

I have created a failing test in: https://github.com/frontity/wp-plugins/commit/bf8e767a0a8f7f29bfa8b6f481dfa2c15a60a359

**Possible solution**

@orballo has suggested to use this approach:

```php
<?php
$dom = new DOMDocument();
$previous_value = libxml_use_internal_errors(TRUE);
$html = $dom->loadHTML('</p>some<p></p>');
libxml_clear_errors();
libxml_use_internal_errors($previous_value);
```

from this post: https://stackoverflow.com/a/7082487/5165454

----

You can use the `malformed-html-in-head-tags` branch.

**Comment by SantosGuillamot** [comment]
@iamuchejude Could you explain here why this issue is blocked and what is needed to unblock it please?
