### ISSUE TITLE
Will fire an error if no nodes are found.

### ISSUE THREAD

**Issue by johnfrancisli** [frontity/wp-plugins#44]
https://github.com/frontity/wp-plugins/blob/f92193c6dc460012e9adfd4664d497ff404a82ca/plugins/frontity-headtags/includes/class-frontity-headtags.php#L163

This fires an error on situations when it tries to grab the head but no head is set because it will look for a childNode on something null. 

Ideally we should have a check like:
`$dom_node = $dom->getElementsByTagName( 'head' )[0];
		$nodes = $dom_node ? $dom_node->childNodes : [];`

Let me know if it makes sense?

**Comment by luisherranz** [comment]
Sounds good to me @johnfrancisli 🙂

Would you mind doing a PR with that change?

**Comment by johnfrancisli** [comment]
Sorry didn't see this until now.

**Comment by luisherranz** [comment]
@johnfrancisli no problem! 😄 

@darerodz can you take a look at the PR and run the tests locally?
