### ISSUE TITLE
REST API - Head Tags doesn't work with AIOSEOP ^4.0.0 [13pt]

### ISSUE THREAD

**Issue by DAreRodz** [frontity/wp-plugins#46]
Our Head Tags plugin stopped working with the All In One SEO Pack plugin after they released the 4.0.0 version.

As the new version is a major refactor, we would have to take a deep look into the new code in order to update our AIOSEOP integration accordingly.

My guess is that finding the specific problem involved and come up with a proper solution would be a time-consuming task.

The issue was found while working on https://github.com/frontity/frontity/pull/664

**Comment by DAreRodz** [comment]
@SantosGuillamot could you assign a priority value to this issue before taking a deeper look?

**Comment by SantosGuillamot** [comment]
I've seen that, since 4.0, [All In One plugin uses the REST API](https://aioseo.com/docs/aioseo-uses-rest-api/). Do you think this will be useful to adapt our plugin?

**Comment by luisherranz** [comment]
For what they say in those docs it seems like the plugin UI is the one using the REST API, probably to retrieve and save the settings.

It doesn't seem like they are exposing the head tags in the entities of the REST API like Yoast.

**Comment by DAreRodz** [comment]
Hey folks! It seems that there's no problem with the new version in the end. As I opened this issue because the e2e tests were failing, I think the problem could be related to some incompatibility between the DB content and the new plugin version.

I'm going to create a new test suite for AIOSEO v4 using a clean DB and check if it works without having to modify this plugin.

**Comment by DAreRodz** [comment]
I've found why the AIOSEO tags are missing for the second and following entities.

1. The callback that AIOSEO attaches to the `wp_head` hook is [`init()`](https://plugins.trac.wordpress.org/browser/all-in-one-seo-pack/trunk/app/Common/Main/Head.php#L30) (/app/Common/Main/Head.php) 
2. Inside that function, [`output()`](https://plugins.trac.wordpress.org/browser/all-in-one-seo-pack/trunk/app/Common/Main/Head.php#L90) is called. 
3. `output()` runs a [bunch of several .php](https://plugins.trac.wordpress.org/browser/all-in-one-seo-pack/trunk/app/Common/Main/Head.php#L168) files - called [views](https://plugins.trac.wordpress.org/browser/all-in-one-seo-pack/trunk/app/Common/Views/main) - to render the meta tags **but using `require_once()`**, so `output()` only works the first time is executed.

If we write an integration for AIOSEO v4, we should override that `option()` function somehow.

**Comment by DAreRodz** [comment]
I've opened an issue in the AIOSEO plugin's support page. I'm gonna set this as `blocked` until they respond.

https://wordpress.org/support/topic/issue-exposing-meta-tags-in-the-rest-api/

**Comment by luisherranz** [comment]
They were fast 🙂

**Comment by DAreRodz** [comment]
Yeah, they are going to fix it in their plugin and it's going to be released in the next version. :relaxed:

**Comment by DAreRodz** [comment]
By the way, we would still have to write an integration, but it'll be a simple one.

**Comment by SantosGuillamot** [comment]
I've seen that they already released a [new version (4.0.16)](https://plugins.trac.wordpress.org/browser/all-in-one-seo-pack/tags/4.0.16/app/Common/Main/Head.php), and it seems the issue is solved.

I've done a quick test and it seems the `head_tags` field is being populated correctly, including the second and following entities. @DAreRodz Could you please confirm this solves the issue that was blocking us?

**Comment by DAreRodz** [comment]
I didn't try this locally yet, but they've changed the [code](https://plugins.trac.wordpress.org/browser/all-in-one-seo-pack/trunk/app/Common/Main/Head.php#L173): now they're using `require` instead of `require_once`! :tada: 

https://plugins.trac.wordpress.org/browser/all-in-one-seo-pack/trunk/app/Common/Main/Head.php#L173

I think we still have to write an integration to handle the `<title>` tag. I'll take a look later.

**Comment by DAreRodz** [comment]
Looks like not only the `<title>` but the `<link rel="canonical">` tag is failing as well, at least for authors, categories and types.
